### ISSUE TITLE
ソーススクリプトが長文の場合極端に重くなる

### ISSUE THREAD

**Issue by UMAGODi** [vain0x/knowbug#101]
スーススクリプトが長文な場合にF5でデバッグ実行起動時にknowbugが極端に重くなる現象があります。標準デバッガでは起こらない、短いスクリプトだと重くならない 等の理由からknowbugのスクリプト表示機能によるものだと推測できます。

環境
Windows 10 Home 64-bit v1909
エディタ：Visual Studio Code 1.43.0
HSP3：hsp36beta
コンパイラ：hspc.exe -Crdwi
デバッガ：knowbug v2.0.2
スクリプト行数：923行

**Comment by vain0x** [comment]
ご報告ありがとうございます。スクリプトに改行やタブ文字が多く含まれていると重くなるようです。

#### 調査

- ソースコードのリクエストが複数回発行されることがある (修正済み)
- タブ文字や改行文字のエスケープ解除が重い: https://github.com/vain0x/knowbug/blob/5f3f8058a6d182e78d140a65e53cc0e486af1a93/src/knowbug_client/mod_knowbug_protocol.hsp#L81-L93

**Comment by vain0x** [comment]
v2.0.3 で改善したと思います。ありがとうございました。

原因:

- スペース ` ` がすべて `\x20` にエスケープされる仕様だったので、これを1つ1つ ` ` に置き換えていくのが遅かったです。改行が `\x0d\x0a` にエスケープされているのも同様。
