### ISSUE TITLE
デバッグウィンドウの表示位置について

### ISSUE THREAD

**Issue by UMAGODi** [vain0x/knowbug#108]
当方の環境では、タスクバーを小さなアイコン＆2段で表示しているのですが、HSPデバッグ時のknowbugの初期位置が少し下に下がりタスクバーに隠れてしまいます。

現在のバージョンではおそらく定数でタスクバーの高さを決めているのではないかと思います。(以前何かでタスクバーの高さの取得方法が分からないとの旨を見た気がしてそう思ったのですが、間違っていたら申し訳ございません。)

タスクバーの高さを除いたエリア＝ワークエリアのサイズはSystemParametersInfoのSPI_GETWORKAREAで取得可能です。この関数で得られるエリアはタスクバーの位置(左右上下)にも対応しているので、この関数を使えば適切な表示領域を得られると思います。

**Comment by vain0x** [comment]
ありがとうございます！
