### ISSUE TITLE
文字化け (v2)

### ISSUE THREAD

**Issue by UMAGODi** [vain0x/knowbug#57]
v2.0.84にてメニューバーと下部のボタンが文字化けしています。ツリーとビューウィンドウの内容は正常に表示されていました。

**Comment by vain0x** [comment]
ご報告ありがとうございました。

おそらく原因は appveyor サーバのシステムロケールが日本語ではないために shift_jis が解釈されないことです。ロケールを変更する方法もあるようですが、いったん自動デプロイは停止しました。
