### ISSUE TITLE
64bitランタイムにおける文字化け

### ISSUE THREAD

**Issue by UMAGODi** [vain0x/knowbug#65]
HSP: hsp36beta
knowbug: 2.0.0-beta
ランライム: hsp64 (hsp3_64.as)

[全般]タブ、str型変数における2バイト文字などの表示がビューウィンドウで文字化けします。
HSP側が36betaで64bitランタイムの規定文字コードをutf8に変更したのが原因だと思われます。hsp3utfでは発生しません。
ソースコードをutf8で記述した場合は[スクリプト]タブでの表示も文字化けします。

どちらもベータということで対応は難しいかもしれませんが一応報告しておきます。

**Comment by UMAGODi** [comment]
失礼しました。issueをよく見ていなくて内容が被ってしまいました…

**Comment by vain0x** [comment]
ご報告ありがとうございます。(自己解決されたようですが) 64ビット版は HSP 3.6 が正式版になってから UTF-8 に切り替える予定です。分かりにくいのでリリースノートにも書いておきます。refs #58

**Comment by vain0x** [comment]
v2.0.0-beta2 から64ビットUTF-8版も同梱することにしました。
