### ISSUE TITLE
設定ファイルが開けない・読み込めない

### ISSUE THREAD

**Issue by vain0x** [vain0x/knowbug#99]
参考: http://hsp.tv/play/pforum.php?mode=all&num=89087

**Comment by skymonsters-Ks** [comment]
はじめまして！
Release より knowbug-v2.0.2.zip をダウンロードしてインストールしたのですが、knowbug.conf が上手く読み込まれていない（変更が反映されない）ので原因を調べていたところ、zip にパッケージされた設定ファイルの改行コードが LF でノートパッド命令が改行を処理できていないためでした。設定ファイルの改行コードを CR+LF に変換すると上手く読み込んでくれるようになりました。
プロジェクトを Clone した中にある設定ファイルは CR+LF だったので zip 圧縮された際に変換されたのではないでしょうか。

**Comment by vain0x** [comment]
ありがとうございます。

knowbug.conf が LF になったのは Git の影響だと思います。Git にはテキストファイルの改行コードを LF/CRLF に自動変換する機能があって、Windows 版のデフォルトでは以下のように動きます。

- 手元のファイルを Git リポジトリに入れる (commit する) とき CRLF → LF に変換する
- Git リポジトリからファイルを取り出す (restore する) とき LF → CRLF に変換する

前者の機能のため、knowbug.conf は Git リポジトリ内では LF で保存されています。@skymonsters-Ks さんの手元で git clone したタイミングで、後者の変換により CRLF になったのだと思います。

私は設定で CRLF への変換を無効化しているので、いま手元にあるソースコードの knowbug.conf は LF です。zip 内の knowbug.conf が LF なのはこれが原因です。また、私のテスト用の HSP ディレクトリにある knowbug.conf はコピーして作ったのではなく、テキストエディタで直接作ったために CRLF の改行コードでした。(ややこしい)

**Comment by vain0x** [comment]
対処

- 最新版の zip ファイルを上げなおしたので、今後ダウンロードした人は問題ないです
- 次のバージョンからは LF 改行でも動作します
